
insert into PROPERTY (PROPERTYID, PROPERTYDESCRIPTION, PROPERTYTYPE, PROPERTYSIZE, PROPERTYADDRESS, SELLINGPRICE, NUMBEROFROOMS, TRANSACTIONSTATUS, CURRENTBID) values (PROPERTIES_SEQ.nextval, 'House', 'FLAT', 2.5, 'Oxgangs Row', 250, 3, 'SOLD', 0);
insert into PROPERTY (PROPERTYID, PROPERTYDESCRIPTION, PROPERTYTYPE, PROPERTYSIZE, PROPERTYADDRESS, SELLINGPRICE, NUMBEROFROOMS, TRANSACTIONSTATUS, CURRENTBID) values (PROPERTIES_SEQ.nextval, 'House', 'FLAT', 2.5, 'Oxgangs Row', 250, 3, 'FOR_SALE', 0);
insert into PROPERTY (PROPERTYID, PROPERTYDESCRIPTION, PROPERTYTYPE, PROPERTYSIZE, PROPERTYADDRESS, SELLINGPRICE, NUMBEROFROOMS, TRANSACTIONSTATUS, CURRENTBID) values (PROPERTIES_SEQ.nextval, 'House', 'FLAT', 2.5, 'Edinburgh', 250, 3, 'FOR_SALE', 0);
insert into PROPERTY (PROPERTYID, PROPERTYDESCRIPTION, PROPERTYTYPE, PROPERTYSIZE, PROPERTYADDRESS, SELLINGPRICE, NUMBEROFROOMS, TRANSACTIONSTATUS, CURRENTBID) values (PROPERTIES_SEQ.nextval, 'House', 'FLAT', 2.5, 'Oxgangs Row', 250, 3, 'FOR_SALE', 0);
insert into PROPERTY (PROPERTYID, PROPERTYDESCRIPTION, PROPERTYTYPE, PROPERTYSIZE, PROPERTYADDRESS, SELLINGPRICE, NUMBEROFROOMS, TRANSACTIONSTATUS, CURRENTBID) values (PROPERTIES_SEQ.nextval, 'House', 'FLAT', 2.5, 'Oxgangs Row', 250, 3, 'FOR_SALE', 0);

insert into USERS (USERID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME, PHONENUMBER, ACCOUNTSTATUS, ACCOUNTTYPE, EMAIL) values (USERS_SEQ.nextval, 'david', 'pass','Zen', 'Pen', 423, 'INACTIVE', 'ADMIN', 'zen_9255@yahoo.com');
insert into USERS (USERID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME, PHONENUMBER, ACCOUNTSTATUS, ACCOUNTTYPE, EMAIL) values (USERS_SEQ.nextval, 'ben', 'ten','Len', 'Ken', 423, 'ACTIVE', 'ADMIN', 'ken_9255@yahoo.com');
insert into USERS (USERID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME, PHONENUMBER, ACCOUNTSTATUS, ACCOUNTTYPE, EMAIL) values (USERS_SEQ.nextval, 'hassan', 'ten', 'Len', 'Fen', 423, 'ACTIVE', 'BUYER', 'pen_9255@yahoo.com');
insert into USERS (USERID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME, PHONENUMBER, ACCOUNTSTATUS, ACCOUNTTYPE, EMAIL) values (USERS_SEQ.nextval, 'dan', 'ten', 'Len', 'Seller', 423, 'ACTIVE', 'SELLER', 'len_9255@yahoo.com');
insert into USERS (USERID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME, PHONENUMBER, ACCOUNTSTATUS, ACCOUNTTYPE, EMAIL) values (USERS_SEQ.nextval, 'ana', 'ten', 'Len', 'Ken', 423, 'ACTIVE', 'ESTATEAGENT', 'ben_9255@yahoo.com');

insert into BIDS (BIDID, BIDAMOUNT, BIDDATE, BIDSTATUS, PROPERTYID) values (BIDS_SEQ.nextval, 250000, '2021-05-26', 'BID_PLACED', 2);